# Wave 2: Prometheus (scrapea métricas de la API y del cluster).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DanielDiazCruz/MLOps-Engineering.git
    targetRevision: main
    path: k8s/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
