apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops
resources:
  - secret.yaml
  - configmap-datasource.yaml
  - configmap-dashboard-provider.yaml
  - configmap-dashboard-json.yaml
  - deployment.yaml
  - service.yaml
