apiVersion: v1
kind: Service
metadata:
  name: data-api-service
  namespace: mlops
  labels:
    app: data-api
spec:
  type: ClusterIP
  selector:
    app: data-api
  ports:
    - name: http
      port: 80
      targetPort: 80
